namespace Pokemon.Battle.Application.Attack;

internal static class TypeMatchupChart
{
    internal static Dictionary<BattleType, IEnumerable<(BattleType, double)>> GetTypeMatchupChart()
    {
        return new Dictionary<BattleType, IEnumerable<(BattleType, double)>>()
        {
            {
                BattleType.Normal, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 0.5),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 0),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Fighting, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 2),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 0.5),
                    (BattleType.Poison, 0.5),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 2),
                    (BattleType.Bug, 0.5),
                    (BattleType.Ghost, 0),
                    (BattleType.Steel, 2),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 0.5),
                    (BattleType.Ice, 2),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 2),
                    (BattleType.Fairy, 0.5),
                }
            },
            {
                BattleType.Flying, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 0.5),
                    (BattleType.Bug, 2),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 2),
                    (BattleType.Electric, 0.5),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Poison, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 0.5),
                    (BattleType.Ground, 0.5),
                    (BattleType.Rock, 0.5),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 0.5),
                    (BattleType.Steel, 0),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 2),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 2),
                }
            },
            {
                BattleType.Ground, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 0),
                    (BattleType.Poison, 2),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 2),
                    (BattleType.Bug, 0.5),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 2),
                    (BattleType.Fire, 2),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 0.5),
                    (BattleType.Electric, 2),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Rock, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 0.5),
                    (BattleType.Flying, 2),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 0.5),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 2),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 2),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 2),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Bug, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 0.5),
                    (BattleType.Flying, 0.5),
                    (BattleType.Poison, 0.5),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 0.5),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 0.5),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 2),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 2),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 2),
                    (BattleType.Fairy, 0.5),
                }
            },
            {
                BattleType.Ghost, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 0),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 2),
                    (BattleType.Steel, 1),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 2),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 0.5),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Steel, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 2),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 0.5),
                    (BattleType.Water, 0.5),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 0.5),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 2),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 2),
                }
            },
            {
                BattleType.Fire, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 0.5),
                    (BattleType.Bug, 2),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 2),
                    (BattleType.Fire, 0.5),
                    (BattleType.Water, 0.5),
                    (BattleType.Grass, 2),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 2),
                    (BattleType.Dragon, 0.5),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Water, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 2),
                    (BattleType.Rock, 2),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 1),
                    (BattleType.Fire, 2),
                    (BattleType.Water, 0.5),
                    (BattleType.Grass, 0.5),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 0.5),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Grass, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 0.5),
                    (BattleType.Poison, 0.5),
                    (BattleType.Ground, 2),
                    (BattleType.Rock, 2),
                    (BattleType.Bug, 0.5),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 0.5),
                    (BattleType.Water, 2),
                    (BattleType.Grass, 0.5),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 0.5),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Electric, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 2),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 0),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 1),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 2),
                    (BattleType.Grass, 0.5),
                    (BattleType.Electric, 0.5),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 0.5),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Psychic, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 2),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 2),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 0.5),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 0),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Ice, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 2),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 2),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 0.5),
                    (BattleType.Water, 0.5),
                    (BattleType.Grass, 2),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 0.5),
                    (BattleType.Dragon, 2),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 1),
                }
            },
            {
                BattleType.Dragon, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 1),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 1),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 2),
                    (BattleType.Dark, 1),
                    (BattleType.Fairy, 0),
                }
            },
            {
                BattleType.Dark, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 0.5),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 1),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 2),
                    (BattleType.Steel, 1),
                    (BattleType.Fire, 1),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 2),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 1),
                    (BattleType.Dark, 0.5),
                    (BattleType.Fairy, 0.5),
                }
            },
            {
                BattleType.Fairy, new List<(BattleType, double)>()
                {
                    (BattleType.Normal, 1),
                    (BattleType.Fighting, 2),
                    (BattleType.Flying, 1),
                    (BattleType.Poison, 0.5),
                    (BattleType.Ground, 1),
                    (BattleType.Rock, 1),
                    (BattleType.Bug, 1),
                    (BattleType.Ghost, 1),
                    (BattleType.Steel, 0.5),
                    (BattleType.Fire, 0.5),
                    (BattleType.Water, 1),
                    (BattleType.Grass, 1),
                    (BattleType.Electric, 1),
                    (BattleType.Psychic, 2),
                    (BattleType.Ice, 1),
                    (BattleType.Dragon, 2),
                    (BattleType.Dark, 2),
                    (BattleType.Fairy, 1),
                }
            },
        };
    }
}